### ISSUE TITLE
get_software_versions is missing entries for multiqc and fasterq-dump

### ISSUE THREAD

**Issue by zmaas** [Dowell-Lab/Nascent-Flow#7]
When running the pipeline, the python script scrape_software_versions.py will exit with a fatal error because the script in get_software_versions does not create the files `v_multiqc.txt` or `v_fasterq-dump.txt`. This error stops the rest of the pipeline from running. There are two ways to fix this:
- Properly create the files in main.nf
- Stop checking for those files in scrape_software_versions.py

This issue was discovered while working on #6

**Comment by magruca** [comment]
Unfortunately this comes down to a Fiji dependency conflict issue with all of the Python packages which is why it hasn't been resolved and those have been commented out for the time being. If you find a good way to get around this, let me know! Otherwise it's kind of low on my to-do list.

**Comment by magruca** [comment]
Just re-read this -- I was reading fasterq-dump as parallel-fastq-dump in my head. fasterq-dump will give the same version as fastq-dump (which is just sra tools), so it doesn't matter there. New versions of the pipeline no longer use fasterq-dump as it creates a lot of network issues with sra tools if the sra files are too large. parallel-fastq-dump I'm not going to include at this moment simply because it's not required in the install and I'm not sure if it's in conda -- I'll double check this and revise as necessary, though.

I fixed the issue with multiqc scraping, though, so that will be pushed shortly. That said I'm going to close this up.

**Comment by magruca** [comment]
@zmaas one other thing... these components were issues with an older version of the pipeline and I don't think have been issues for a while. I would double check that you're using the latest commit. When we include the new version to the main nf-core with multicov/fstitch/tfit/dastk, I'll update to a new version of the pipeline.
